# Generated by Django 3.2.7 on 2021-10-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='students_at_Italian_school',
            field=models.IntegerField(default=1),
        ),
    ]
