# Generated by Django 3.2.8 on 2021-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20211010_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='library_card_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supporter',
            field=models.BooleanField(default=False),
        ),
    ]
